# Generated by Django 5.1.7 on 2025-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to=''),
        ),
    ]
