# Generated by Django 5.1.7 on 2025-03-23 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('max_players', models.IntegerField(default=2)),
                ('score', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('timer_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, default='', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_import', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_player', to=settings.AUTH_USER_MODEL)),
                ('player_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.team')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField()),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('rounds', models.IntegerField(default=0, null=True)),
                ('max_rounds', models.IntegerField(default=4, null=True)),
                ('max_players', models.IntegerField(default=4, null=True)),
                ('word_to_guess', models.CharField(blank=True, max_length=30, null=True)),
                ('current_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='game.player')),
                ('past_artists', models.ManyToManyField(related_name='has_drawn', to='game.player')),
                ('guessers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_guessers', to='game.team')),
                ('team1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_team1', to='game.team')),
                ('team2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_team2', to='game.team')),
                ('game_timer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.timer')),
                ('past_words', models.ManyToManyField(related_name='past_word', to='game.wordbank')),
            ],
        ),
    ]
