# Generated by Django 5.1.7 on 2025-04-24 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message_sender',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='time_send',
            new_name='time_sent',
        ),
    ]
