# Generated by Django 5.1.7 on 2025-04-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_message_sender_chatmessage_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='player',
        ),
    ]
