# Generated by Django 5.1.7 on 2025-04-27 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatmessage_player'),
        ('game', '0008_player_alltime_score_player_player_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player'),
        ),
    ]
