# Generated by Django 5.1.7 on 2025-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='past_artists',
            field=models.ManyToManyField(related_name='past_artists', to='game.player'),
        ),
    ]
