# Generated by Django 5.1.7 on 2025-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_past_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='past_artists',
            field=models.ManyToManyField(blank=True, related_name='past_artists', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='past_words',
            field=models.ManyToManyField(blank=True, related_name='past_word', to='game.wordbank'),
        ),
    ]
