# Generated by Django 5.1.7 on 2025-04-21 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_past_artists_alter_game_past_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alltime_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='game.game'),
        ),
        migrations.AddField(
            model_name='team',
            name='current_players',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='rounds',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='game.team'),
        ),
    ]
